name: publish

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  push_to_registry:
    name: build and release
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - id: check-changes
      uses: hashibuto/github-actions/changes-check@changes-check_v0
      with:
        base-branch: master

    - id: check-version
      name: Check release version
      uses: hashibuto/github-actions/version-check@version-check_v0
      with:
        filename: pyproject.toml
        path-prefix: ./
        expression: version = \"(.*)\"

    - name: install poetry
      run: pip install poetry==1.7.0

    - name: login to poetry
      uses: hashibuto/github-actions/poetry-login@poetry-login_v0
      with:
        name: pubreg
        repository: https://pypi.org/legacy/
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}

    - name: login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build python release
      run: poetry build

    - name: publish python release
      if: ${{ needs.evaluate-changed-items.outputs.is-merged == 'true' }}
      run: poetry publish --repository pubreg

    - id: tag-release-version
      name: Tag release version
      if: ${{ needs.evaluate-changed-items.outputs.is-merged == 'true' }}
      uses: hashibuto/github-actions/version-check@version-check_v0
      with:
        filename: pyproject.toml
        path-prefix: ./
        create-release-tag: true
        create-major-release-tag: false

    - name: Update compare tag
      if: ${{ needs.evaluate-changed-items.outputs.is-merged == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "tags/base",
            sha: "${{ github.sha }}",
            force: true
          })